config/routes.rb
Rails.application.routes.draw do
  root 'notes#new'
  resources :users, except: [:index]
  resources :notes, except: [:index]
  resources :videos, except: [:index, :show]
  resources :stamps, except: [:index]
  resources :sessions, only: [:create, :new, :destroy]

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :title, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :videos, dependent: :destroy
  has_many :stamps, dependent: :destroy
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
  validates :note_id, presence: true

  belongs_to :notes
end

app/models/user.rb
class User < ActiveRecord::Base
   validates :username, presence: true
   validates :email, presence: true, uniqueness: true
   has_secure_password

   has_many :notes, dependent: :destroy
   has_many :videos, through: :notes
   has_many :stamps, through: :notes
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, presence: true
  validates :link, presence: true

  belongs_to :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include CurrentUserHelper
  include SortTimeHelper
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    note = Note.new(note_params)
    if note.save
      redirect_to note_path(note)
    else
      flash[:note_create_error] = "Error creating note"
      render :new
    end
  end

  def new
  end

  def show
    @note = Note.find(params[:id])
    redirect_to user_path(current_user) unless current_user.notes.include?(@note)
  end

  def update
    note = Note.find(params[:id])
      if note.update_attributes(note_params)
        redirect_to note_path(note)
      else
        flash[:note_update_error] = "Error updating note"
        render :edit
      end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end

  private

  def note_params
    params.require(:note).permit(:title, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:user_login_error] = "Error on login"
      render :new
    end
  end

  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController

  def create
    stamp = Stamp.new(stamp_params)
    if stamp.save
      redirect_to note_path(stamp.note_id)
    else
      flash[:stamp_create_error] = "Error creating TimeStamp"
      render :new
    end
  end

  def new
  end

  def show
    @stamp = Stamp.find(params[:id])
  end

  def update
    stamp = Stamp.find(params[:id])
    if stamp.update_attributes(stamp_params)
      redirect_to note_path(stamp.note_id)
    else
      flash[:stamp_update_error] = "Error updating TimeStamp"
      render :edit
    end
  end

  def edit
    @stamp = Stamp.find(params[:id])
  end

  def destroy
    @stamp = Stamp.find(params[:id])
    Stamp.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to note_path(@stamp.note_id) }
      format.js
    end
  end

  private

  def stamp_params
    params.require(:stamp).permit(:time, :body, :note_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash[:user_create_error] = "Error registering"
      render :new
    end
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user.id == @user.id
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      redirect_to user_path(user)
    else
      flash[:user_update_error] = "Error updating"
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to edit_user_path(current_user) unless current_user.id == @user.id
  end

  def destroy
    User.find(session[:user_id]).destroy
    reset_session
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def create
    video = Video.new(video_params)
    @note = Note.find(video.note_id)
    # respond_to do |format|
      if video.save
        #  format.html { redirect_to note_path(video.note_id) }
         redirect_to note_path(video.note_id)
        #  format.js
      else
        flash[:video_create_error] = "Error creating video"
        redirect_to note_path(video.note_id)
      end
    # end
  end

  def new
  end

  def update
    video = Video.find(params[:id])
    if video.update_attributes(video_params)
      redirect_to note_path(video.note_id)
    else
      flash[:video_update_error] = "Error updating video"
      render :edit
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def destroy
    video = Video.find(params[:id])
    Video.find(params[:id]).destroy
    redirect_to note_path(video.note_id)
  end

  private

  def video_params
    params.require(:video).permit(:title, :link, :note_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/current_user_helper.rb
module CurrentUserHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/sort_time_helper.rb
module SortTimeHelper

  def seconds_converter(formated_time)
    if formated_time.match(/([0-9]*):([0-9]*)/)
      minutes = formated_time.match(/([0-9]*)/)[0]
      seconds = formated_time.match(/\:([0-9]*)/)[1]
      return (minutes.to_i * 60) + seconds.to_i
    else
      return formated_time = 0
    end
  end

  def sort_time(array)
    array.sort_by do |stamp|
      seconds_converter(stamp.time)
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YoutubeNoteTaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
</head>
<body>

  <nav>
    <div class='nav-wrapper'>
      <%= link_to "TimeStamps", root_url, class: 'brand-logo' %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id='nav-mobile' class='right hide-on-med-and-down'>
        <li> <%= link_to 'new note', root_url %> </li>
        <%= render '/sessions/login' %>
      </ul>
      <ul class='side-nav' id='mobile-demo'>
        <%= render '/sessions/login' %>
      </ul>
    </div>
  </nav>

  <main>
    <div class='container'>
      <%= yield %>
    </div>
  </main>

  <footer class='page-footer'>
    <div class='footer-copyright'>
      <div class='container'>
        &copy 2016 Time-Stamps.herokuapp.com
      </div>
    </div>
  </footer>

</body>
</html>

app/views/notes/_delete.html.erb
<%= form_for :not, method: :delete, url: note_path(@note.id), data: { confirm: "are you sure?" } do |f| %>
  <%= f.submit :delete %>
<% end %>

app/views/notes/_edit.html.erb
<div class='edit'>
  <div class='row'>
    <%= form_for :note, method: :put, url: note_path, id: "form-note", remote: true do |f| %>
      <div class='col s4'>
        <%= f.text_field :title, placeholder: "#{@note.title}", id: 'note-title' %>
      </div>
      <div class='col'>
        <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
          <i class='large material-icons'>done</i>
        <% end %>
      </div>
    <% end %>
    <div class='col'>
      <%= link_to ("<i class='large material-icons'>delete</i>").html_safe, @note, method: :delete, url: note_path(@note.id), data: { confirm: "are your sure?" }, class: "btn-floating btn waves-effect waves-light red", title: 'delete' %>
    </div>
  </div>
</div>

app/views/notes/edit.js.erb
$('.note-edit-form').toggle().html("<%= escape_javascript(render partial: 'notes/edit') %>");

$('#note-title').focus();
var savedInput = $('#note-title').val();
$('#note-title').val('');
$('#note-title').val(savedInput);


$('.edit').on('submit', function(){
  var title = $('#note-title').val();
  $('#note-show-title').text(title);
  $('.note-edit-form').toggle();
});

app/views/notes/new.html.erb
<div class='side-pages'>
  <% if current_user %>
    <h3>Get started by making a new note.</h3>
    <%= form_for :note, url: notes_path do |f| %>
      <div>
        <%= f.text_field :title, placeholder: 'title', autofocus: true %>
      </div>
      <div>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div>
        <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
          <i class='large material-icons'>done</i>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h4>Login or register to start making a note.</h4>

    <div class='video-container'>
      <div id="player"></div>
    </div>

    <%= javascript_include_tag "welcome.js" %>
  <% end %>
</div>

app/views/notes/show.html.erb
<header class='boxed-edit'>
  <h3 id='note-show-title'> <%= @note.title %> </h3>
  <p id='note-edit-link'> <%= link_to ("<i class='large material-icons'>mode_edit</i>").html_safe, edit_note_path(@note), remote: true, class: "btn-floating btn waves-effect waves-light blue", title: 'edit' %> </p>
</header>

<div class='note-edit-form' style="display:none;"></div>
<div class='video-show-list' style="display:inline;"><%= render partial: '/videos/show' %></div>

<div class='row'>
  <div class='col s6'>
    <% if @note.videos.size >= 1 %>
      <div class='video-container'>
        <div id="player"></div>
      </div>
    <% end %>

    <div>
      <%= render '/stamps/new' %>
    </div>
  </div>

  <div class='col s6'>
      <div class='stamp-show-list' style="display:inline;"><%= render partial: '/stamps/show' %></div>
  </div>
</div>

<%= javascript_include_tag "youtube.js" %>

app/views/notes/show.js.erb
$('.stamp-show-list').html("<%= escape_javascript(render partial: 'stamps/show') %>");

$('#time-input').val("");
$('#textarea1').val("");

app/views/stamps/_delete.html.erb
<%= form_for :stamp, method: :delete, url: stamp_path(stamp.id), data: { confirm: "are you sure?" } do |f| %>
  <%= f.submit :delete %>
<% end %>

app/views/stamps/_edit.html.erb
<%= form_for :stamp, method: :put, url: stamp_path, remote: true do |f| %>
  <div class='row'>
    <div class='col s11'>
      <div>
        <%= f.text_field :time, id: "#{@stamp.id}", placeholder: "#{@stamp.time}" %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col s11'>
      <div class='input-field'>
        <%= f.text_area :body, placeholder: "#{@stamp.body}", id: 'textarea1', class: 'materialize-textarea' %>
      </div>
    </div>
    <div id='body-button' class='col s1'>
      <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
        <i class='large material-icons'>done</i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stamps/_new.html.erb
<div class='stamp-form'>
  <%= form_for :stamp, url: stamps_path, remote: true, id: 'stamp-form' do |f| %>
    <div class='row'>
      <div class='col s1'><div id='get-time' class="btn-floating btn waves-effect waves-light green", title='add'><i class="material-icons">add</i></div></div>
      <div class='col s3'>
        <%= f.text_field :time, placeholder: "time", id: 'time-input' %>
      </div>
    </div>
    <div class='row'>
      <div class='col s11'>
        <div class='input-field'>
            <%= f.text_area :body, placeholder: "body", id: 'textarea1', class: 'materialize-textarea' %>
        </div>
        <div>
          <%= f.hidden_field :note_id, value: @note.id %>
        </div>
      </div>
      <div class='col s1'>
        <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
          <i class='large material-icons'>done</i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/stamps/_show.html.erb
<div id='stamp-list'>
  <% sort_time(@note.stamps).each do |stamp| %>
    <div class="<%= stamp.id %>">
      <div class='row'>
        <ul>
          <li>
            <div class='col s10'>
              <div class='row'>
                <div class='col s2'><div style='cursor:pointer' class='chip hoverable'><%= stamp.time %></div></div>
                <div class='col s10'><div class='wordwrap'><%= stamp.body %></div></div>
              </div>
              <div id="<%= stamp.id %>" style="display:none;"></div>
            </div>
            <div class='col s1'>
              <%= link_to ("<i class='large material-icons'>mode_edit</i>").html_safe, edit_stamp_path(stamp), class: "btn-floating btn-small waves-effect waves-light blue", title: 'edit', remote: true %>
            </div>
            <div class='col s1'>
              <%= link_to ("<i class='large material-icons'>delete</i>").html_safe, stamp, url: stamp_path(stamp.id), method: :delete, data: { confirm: "are you sure?" }, class: "btn-floating btn-small waves-effect waves-light red", title: 'delete', remote: true  %>
            </div>
        </li>
        </ul>
      </div>
    </div>

    <script>
      $('.<%= stamp.id %> .chip').on('click', function(){
        player.seekTo((uglySeconds('#<%=stamp.time%>')));
      })
    </script>

  <% end %>
</div>

app/views/stamps/destroy.js.erb
$('#stamp-list').bind('ajax:success', function(){
  $('.<%= @stamp.id %>').fadeOut();
});

app/views/stamps/edit.js.erb
$('#<%= @stamp.id %>').toggle().html("<%= escape_javascript(render partial: 'stamps/edit') %>");

$("input[id='<%= @stamp.id %>']").focus();
var time = $("input[id='<%= @stamp.id %>']").val();
$("input[id='<%= @stamp.id %>']").val("");
$("input[id='<%= @stamp.id %>']").val(time);

app/views/users/edit.html.erb
<div class='side-pages'>
  <h3>Edit your profile</h3>

  <%= form_for :user, method: :put, url: user_path, id: 'user-form' do |f| %>
    <div>
      <%= f.text_field :username, placeholder: "#{@user.username}", id: 'user-username' %>
    </div>
    <div>
      <%= f.email_field :email, placeholder: "#{@user.email}" %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: "password" %>
    </div>
    <div class='user-edit-buttons'>
      <div class='row'>
        <div class='col s2'>
          <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
            <i class='large material-icons'>done</i>
          <% end %>
        </div>
      <% end %>
        <div class='col s2'>
          <%= link_to ("<i class='large material-icons'>delete</i>").html_safe, @user, url: user_path(@user.id), method: :delete, data: { confirm: "are you sure?" }, class: "btn-floating btn-small waves-effect waves-light red", title: 'delete' %>
        </div>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<div class='side-pages'>
  <h3>Register</h3>

  <%= form_for :user, url: users_path do |f| %>
    <div>
      <%= f.text_field :username, placeholder: 'username', autofocus: true %>
    </div>
    <div>
      <%= f.email_field :email, placeholder: 'email' %>
    </div>
    <div>
      <%= f.password_field :password, placeholder: 'password' %>
    </div>
    <div>
      <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
        <i class='large material-icons'>done</i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='side-pages'>
  <header id='boxed-edit'>
    <h2><%= @user.username %></h2>
    <p id='user-edit'><%= link_to ("<i class='large material-icons'>mode_edit</i>").html_safe, edit_user_path(@user), class: "btn-floating btn waves-effect waves-light blue", title: 'edit' %></p>
  </header>

  <h4>All Notes</h4>


  <table class='highlight'>
    <thead>
      <tr>
          <th data-field="id">Notes</th>
          <th data-field="name">Video Title</th>
          <th data-field="price">Number of TimeStamps</th>
      </tr>
    </thead>
    <% @user.notes.each do |note| %>
    <tbody>
      <tr>
        <td> <%= link_to note.title, note_path(note) %> </td>
        <td> <% note.videos.each do |video| %>
              <%= video.title %>
             <% end %>
        </td>
        <td> <%= note.stamps.size %> </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/videos/_delete.html.erb
<%= form_for :video, method: :delete, url: video_path(video.id), data: { confirm: "are you sure?" } do |f| %>
  <%= f.submit :delete %>
<% end %>

app/views/videos/_edit.html.erb
<div class='video-edit'>
  <%= form_for :video, method: :put, url: video_path, remote: true, class: 'youtube-form' do |f| %>
    <div class='row'>
      <div class='col s4'>
        <div>
          <%= f.text_field :title, placeholder: "#{@video.title}", id: 'video-title-form' %>
        </div>
      </div>
        <div class='col s1'>
          <%= button_tag class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
          <i class='large material-icons'>done</i>
          <% end %>
        </div>
      </div>
    <div class='row'>
      <div class='col s4'>
        <div>
          <%= f.text_field :link, placeholder: "#{@video.link}", class: 'youtube-link' %>
        </div>
      </div>
      <div class='col s1'>
        <%= button_tag id: "reload", class: "btn-floating btn waves-effect waves-light orange", title: 'reload' do %>
          <i class='large material-icons'>input</i>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/videos/_new.html.erb
<div class='video-hook'>
  <h5 class='h5-headers'>New Video</h5>

  <%= form_for :video, url: videos_path, class: 'youtube-form' do |f|%>
    <div class='row'>
      <div class='col s4'>
        <div>
          <%= f.text_field :link, placeholder: "paste youtube link here", class: 'youtube-link', autofocus: true %>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col s4'>
        <div>
          <%= f.text_field :title, placeholder: "title" %>
        </div>
      </div>
      <div>
        <%= f.hidden_field :note_id, value: @note.id %>
      </div>
      <div class='col s1'>
        <div id='video-submit'>
          <%= button_tag id: 'video-submit', class: "btn-floating btn waves-effect waves-light yellow", title: 'submit' do %>
            <i class='large material-icons'>done</i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/videos/_show.html.erb
<div id='video-list'>
  <% @note.videos.each do |video| %>

  <div class='this-thing' style='display:none;'> <%= video.link %> </div>
    <div class='row'>
      <div class='col s4'><h5 id='video-title'><%= video.title %></h5></div>
      <div class='col'>
        <%= link_to ("<i class='large material-icons'>mode_edit</i>").html_safe, edit_video_path(video), class: "btn-floating btn waves-effect waves-light blue", title: 'edit', remote: true %>
      </div>
      <div class='col'>
        <%= link_to ("<i class='large material-icons'>delete</i>").html_safe, video, method: :delete, url: video_path(video.id), data: { confirm: "are you sure?" }, class: "btn-floating btn waves-effect waves-light red", title: 'delete' %>
      </div>
    </div>
  <% end %>
  <div class='video-edit-form' style='display:none;'></div>
</div>

<% if @note.videos.size < 1 %>
  <div class='youtube-new-form'>
    <%= render '/videos/new' %>
  </div>
<% end %>

app/views/videos/create.js.erb
// $('.video-show-list').html("<%= escape_javascript(render partial: 'videos/show') %>");

app/views/videos/edit.js.erb
$('.video-edit-form').toggle().html("<%= escape_javascript(render partial: 'videos/edit') %>")

$('#video-title-form').focus();
var videoTitle = $('#video-title-form').val();
$('#video-title-form').val('');
$('#video-title-form').val(videoTitle);

$('.video-edit').on('submit', function(){
  var title = $('#video-title-form').val();
  $('#video-title').text(title);
  $('.video-edit-form').toggle();
})

$('#reload').on('click', function(){
  location.reload();
})